version: '2.1'
services:
  app:
    build: .
    environment:
      MYAPP_DATABASE_HOST: db
      MYAPP_REDIS_HOST: redis
      MYAPP_WEB_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:8080
  db:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp
  redis:
    image: healthcheck/redis
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
